---
- name: Create directory for NFS export
  file:
    path: "/export/kubernetes"
    state: directory
    mode: "0777"
    owner: "root"
    group: "root"
- name: Update apt
  apt:
    update_cache: yes
    upgrade: yes
- name: Install NFS server
  apt:
    pkg:
      - nfs-kernel-server
- name: Add export entry
  lineinfile:
    path: /etc/exports
    line: "/export/kubernetes    10.0.11.0/255.255.255.0(rw,sync,no_subtree_check,no_root_squash)"
- name: Restart NFS server
  ansible.builtin.systemd:
    name: nfs-kernel-server
    state: restarted
