---
# Install Istio
- name: Get home directory of ansible_ssh_user
  shell: 'getent passwd "{{ ansible_ssh_user }}" | cut -d: -f6'
  register: ansible_ssh_user_home
- name: Install istioctl
  shell: chdir=/opt curl -L https://istio.io/downloadIstio | ISTIO_VERSION=1.10.1 TARGET_ARCH=x86_64 sh -
- name: Set path to the istioctl
  lineinfile:
    dest="{{ ansible_ssh_user_home.stdout }}/.bashrc"
    line={{ item }}
  with_items:
    - "export PATH=$PATH:/opt/istio-1.10.1/bin"
- name: Install Istio
  shell: PATH=$PATH:/opt/istio-1.10.1/bin istioctl install -y

# Install Knative
- name: Install Knative Serving
  shell: |
    kubectl apply -f https://github.com/knative/serving/releases/download/v0.23.0/serving-crds.yaml
    kubectl apply -f https://github.com/knative/serving/releases/download/v0.23.0/serving-core.yaml
    kubectl apply -f https://github.com/knative/net-istio/releases/download/v0.23.0/net-istio.yaml
    kubectl apply -f https://github.com/knative/serving/releases/download/v0.23.0/serving-default-domain.yaml
- name: Install Knative Eventing
  shell: |
    kubectl apply -f https://github.com/knative/eventing/releases/download/v0.23.0/eventing-crds.yaml
    kubectl apply -f https://github.com/knative/eventing/releases/download/v0.23.0/eventing-core.yaml

# Install Cert Manager
- name: Install Cert Manager
  shell: |
    kubectl apply -f https://github.com/jetstack/cert-manager/releases/download/v1.3.1/cert-manager.yaml

# Install KFServing
- name: Get KFServing manifest file
  get_url:
    url: https://github.com/kubeflow/kfserving/releases/download/v0.5.1/kfserving.yaml
    dest: /tmp/kfserving.yaml
    force: yes
- name: Fix KFServing manifest file to use knative gateway
  replace:
    path: /tmp/kfserving.yaml
    regexp: '^(\s+"localGateway" : ).*,$'
    replace: '\1 "knative-local-gateway.knative-serving",'
- name: Fix KFServing manifest file to use knative gateway
  replace:
    path: /tmp/kfserving.yaml
    regexp: '^(\s+"localGatewayService" : ).*,$'
    replace: '\1 "knative-local-gateway.istio-system.svc.cluster.local",'
- name: Install KFServing
  shell: kubectl apply -f /tmp/kfserving.yaml
