---
- name: Update apt
  apt:
    update_cache: yes
    upgrade: yes
- name: Add gpg key for docker
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
- name: Add repo for docker
  ansible.builtin.apt_repository:
    # deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
    state: present
- name: Update apt
  apt:
    update_cache: yes
- name: Install docker
  apt:
    pkg:
      - containerd.io=1.2.13-2
      - docker-ce=5:19.03.11~3-0~ubuntu-focal
      - docker-ce-cli=5:19.03.11~3-0~ubuntu-focal
    force: yes
- name: Copy daemon.json for docker
  copy:
    src: ./daemon.json
    dest: /etc/docker/daemon.json
- name: Make systemd directory
  ansible.builtin.file:
    path: /etc/systemd/system/docker.service.d
    state: directory
    mode: "0755"
- name: Reload daemons
  ansible.builtin.systemd:
    daemon_reload: yes
- name: Restart docker
  ansible.builtin.systemd:
    name: docker
    state: restarted
- name: Enable docker
  ansible.builtin.systemd:
    name: docker
    enabled: true
