---
- name: Download kfctl
  get_url:
    url: https://github.com/kubeflow/kfctl/releases/download/v1.2.0/kfctl_v1.2.0-0-gbc038f9_linux.tar.gz
    dest: /tmp/kfctl_v1.2.0-0-gbc038f9_linux.tar.gz
    force: yes
- name: Create directory for kfctl
  file:
    path: "{{ kf_dir }}"
    state: directory
    mode: "0777"
    owner: "k8s-user"
    group: "k8s-user"
- name: Unarchive kfctl
  ansible.builtin.unarchive:
    src: /tmp/kfctl_v1.2.0-0-gbc038f9_linux.tar.gz
    dest: "{{ kf_dir }}"
- name: Install kubeflow
  shell: "cd {{ kf_dir }} && $KF_DIR/kfctl apply -V -f $CONFIG_URI"
  environment:
    PATH: "$PATH:{{ kf_path }}"
    KF_NAME: "{{ kf_name }}"
    BASE_DIR: "{{ base_dir }}"
    KF_DIR: "{{ kf_dir }}"
    CONFIG_URI: "{{ config_uri }}"
