---
- name: Create namespace 'airflow'
  shell: kubectl create ns airflow

- name: Add helm repository (postgres)
  shell: helm repo add postgres-stable https://charts.bitnami.com/bitnami
- name: Update helm repository
  shell: helm repo update
- name: Install postgresql
  shell: |
    helm install airflow-postgres postgres-stable/postgresql \
      --namespace airflow \
      --set postgresqlDatabase=postgres

- name: Add helm repository (ingress-nginx)
  shell: helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
- name: Update helm repository
  shell: helm repo update
- name: Install ingress-nginx
  shell: |
    helm install ingress-nginx ingress-nginx/ingress-nginx \
      --set controller.service.nodePorts.http=32000 \
      --set controller.service.nodePorts.https=32001

- name: Create secret for redis
  shell: kubectl create secret generic airflow-redis --from-literal=redis-password=$(openssl rand -base64 13) -n airflow

- name: Add helm repository
  shell: helm repo add airflow-stable https://airflow-helm.github.io/charts
- name: Update helm repository
  shell: helm repo update
- name: Install Airflow
  shell: |
    helm install airflow-cluster airflow-stable/airflow \
      --namespace airflow \
      --version 8.1.3 \
      --set airflow.image.tag=2.1.0-python3.8 \
      --set dags.persistence.enabled=true \
      --set dags.persistence.storageClass="" \
      --set dags.persistence.accessMode=ReadOnlyMany \
      --set dags.persistence.size=1Gi \
      --set postgresql.enabled=false \
      --set externalDatabase.host=airflow-postgres-postgresql.airflow.svc.cluster.local \
      --set externalDatabase.port=5432 \
      --set externalDatabase.database=postgres \
      --set externalDatabase.user=postgres \
      --set externalDatabase.passwordSecret=airflow-postgres-postgresql \
      --set externalDatabase.passwordSecretKey=postgresql-password \
      --set redis.master.persistence.enabled=true \
      --set redis.slave.persistence.enabled=true \
      --set redis.existingSecret=airflow-redis \
      --set redis.existingSecretPasswordKey=redis-password \
      --set logs.persistence.enabled=true \
      --set logs.persistence.storageClass="" \
      --set logs.persistence.accessMode=ReadWriteMany \
      --set logs.persistence.size=1Gi \
      --set airflow.config.AIRFLOW__WEBSERVER__BASE_URL="http://k8s-controlplane-1/airflow" \
      --set airflow.config.AIRFLOW__CELERY__FLOWER_URL_PREFIX="/airflow/flower" \
      --set ingress.enabled=true \
      --set ingress.web.path="/airflow" \
      --set ingress.web.flower="/airflow/flower"
