---
- name: Create namespace 'airflow'
  shell: kubectl create ns airflow

- name: Add helm repository
  shell: helm repo add postgres-stable https://charts.bitnami.com/bitnami
- name: Update helm repository
  shell: helm repo update
- name: Install postgresql
  shell: |-
    helm install postgres-cluster postgres-stable/postgresql
      --namespace airflow
      --set postgresqlPostgresPassword=airflow-db-postres-pass
      --set postgresqlUsername=airflow-db-user
      --set postgresqlPassword=airflow-db-pass
      --set postgresqlDatabase=airflow-db

- name: Add helm repository
  shell: helm repo add airflow-stable https://airflow-helm.github.io/charts
- name: Update helm repository
  shell: helm repo update
- name: Install NFS provisioner
  shell: |-
    helm install airflow-cluster airflow-stable/airflow
      --namespace airflow
      --version 8.1.3
      --set web.service.nodePort.http=31000
      --set web.service.type=NodePort
      --set postgresql.enabled=false
      --set externalDatabase.host=postgres-cluster-postgresql.airflow.svc.cluster.local
      --set externalDatabase.port=5432
      --set externalDatabase.database=airflow-db
      --set externalDatabase.user=airflow-db-user
      --set externalDatabase.passwordSecret=airflow-db-pass

