---
kernel_params:
  - key: net.bridge.bridge-nf-call-ip6tables
    value: 1
  - key: net.bridge.bridge-nf-call-iptables
    value: 1
firewall_alternatives:
  - name: iptables
    path: /usr/sbin/iptables-legacy
  - name: ip6tables
    path: /usr/sbin/ip6tables-legacy
  - name: arptables
    path: /usr/sbin/arptables-legacy
  - name: ebtables
    path: /usr/sbin/ebtables-legacy