---
- hosts: controlplane[0]
  gather_facts: false
  become: yes
  roles:
    - setup_controlplane_node

- hosts: worker
  gather_facts: false
  become: yes
  roles:
    - setup_worker_node
