---
- name: Setup controlplane node
  shell: kubeadm init --apiserver-advertise-address={{hostvars[groups.controlplane[0]].ansible_host}} --pod-network-cidr=10.244.0.0/16

- name: Create .kube directory for root
  file:
    path: "/root/.kube/"
    state: directory
    mode: "0755"
    owner: "root"
    group: "root"

- name: Copy admin.conf for root
  copy:
    src: /etc/kubernetes/admin.conf
    dest: "/root/.kube/config"
    owner: "root"
    group: "root"
    mode: "0600"
    remote_src: yes

- name: Get home directory of ansible_ssh_user
  shell: 'getent passwd "{{ ansible_ssh_user }}" | cut -d: -f6'
  register: ansible_ssh_user_home

- name: Create .kube directory for ansible_ssh_user
  file:
    path: "{{ ansible_ssh_user_home.stdout }}/.kube/"
    state: directory
    mode: "0755"
    owner: "{{ ansible_ssh_user }}"
    group: "{{ ansible_ssh_user }}"

- name: Copy admin.conf for ansible_user_id
  copy:
    src: /etc/kubernetes/admin.conf
    dest: "{{ ansible_ssh_user_home.stdout }}/.kube/config"
    owner: "{{ ansible_ssh_user }}"
    group: "{{ ansible_ssh_user }}"
    mode: "0600"
    remote_src: yes

- name: Download Calico's manifest file
  get_url:
    url: https://docs.projectcalico.org/manifests/calico.yaml
    dest: /tmp/calico.yaml
    force: yes

- name: Install Calico
  shell: kubectl apply -f /tmp/calico.yaml

- name: Create token for adding node
  shell: kubeadm token create
  register: kubeadm_token

- name: Get ca cert
  shell: openssl x509 -pubkey -in /etc/kubernetes/pki/ca.crt | openssl rsa -pubin -outform der 2>/dev/null | openssl dgst -sha256 -hex | sed 's/^.* //'
  check_mode: false
  changed_when: false
  register: kubeadm_ca_cert

- name: Download helm's installation script
  get_url:
    url: https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
    dest: /tmp/get-helm-3
    force: yes
- name: Install helm
  shell: bash /tmp/get-helm-3
- name: Add helm repository
  shell: helm repo add nfs-subdir-external-provisioner https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner/
- name: Update helm repository
  shell: helm repo update
- name: Install NFS provisioner
  shell: helm install nfs-subdir-external-provisioner --set nfs.server={{hostvars[groups.nfs[0]].ansible_host}} --set nfs.path=/export/kubernetes --set storageClass.name=nfs --set storageClass.defaultClass=true nfs-subdir-external-provisioner/nfs-subdir-external-provisioner
